import type { TemplateConfig } from '../shared/types';

export const templates: TemplateConfig[] = [
  {
    id: 'classic',
    name: 'Classic',
    thumbnail: '',
    colors: { primary: '#1a1a1a', accent: '#1a1a1a', text: '#1a1a1a', background: '#FFFFFF' },
    fonts: { heading: '"EB Garamond", Georgia, serif', body: '"EB Garamond", Georgia, serif' },
    layout: 'single-column',
    atsScore: 100,
    category: 'professional',
  },
  {
    id: 'modern',
    name: 'Modern',
    thumbnail: '',
    colors: { primary: '#1B2A4A', accent: '#3B82F6', text: '#374151', background: '#FFFFFF', sidebar: '#1B2A4A' },
    fonts: { heading: '"Inter", system-ui, sans-serif', body: '"Inter", system-ui, sans-serif' },
    layout: 'two-column',
    atsScore: 95,
    category: 'professional',
  },
  {
    id: 'creative',
    name: 'Creative',
    thumbnail: '',
    colors: { primary: '#7C3AED', accent: '#F59E0B', text: '#1F2937', background: '#FFFFFF' },
    fonts: { heading: '"Poppins", system-ui, sans-serif', body: '"Poppins", system-ui, sans-serif' },
    layout: 'single-column',
    atsScore: 85,
    category: 'creative',
  },
  {
    id: 'minimal',
    name: 'Minimal',
    thumbnail: '',
    colors: { primary: '#0a0a0a', accent: '#0a0a0a', text: '#374151', background: '#FFFFFF' },
    fonts: { heading: '"DM Sans", system-ui, sans-serif', body: '"DM Sans", system-ui, sans-serif' },
    layout: 'single-column',
    atsScore: 98,
    category: 'minimal',
  },
  {
    id: 'executive',
    name: 'Executive',
    thumbnail: '',
    colors: { primary: '#1A1A2E', accent: '#C9A84C', text: '#2a2a2a', background: '#FAFAF8' },
    fonts: { heading: '"Cormorant Garamond", Georgia, serif', body: '"Lato", system-ui, sans-serif' },
    layout: 'two-column',
    atsScore: 92,
    category: 'professional',
  },
  {
    id: 'horizon',
    name: 'Horizon',
    thumbnail: '',
    colors: { primary: '#1E3A5F', accent: '#38BDF8', text: '#1e293b', background: '#FFFFFF' },
    fonts: { heading: '"DM Sans", system-ui, sans-serif', body: '"DM Sans", system-ui, sans-serif' },
    layout: 'two-column',
    atsScore: 93,
    category: 'professional',
  },
  {
    id: 'compact',
    name: 'Compact',
    thumbnail: '',
    colors: { primary: '#111827', accent: '#6366F1', text: '#374151', background: '#FFFFFF' },
    fonts: { heading: '"Inter", system-ui, sans-serif', body: '"Inter", system-ui, sans-serif' },
    layout: 'single-column',
    atsScore: 97,
    category: 'minimal',
  },
  {
    id: 'elegant',
    name: 'Elegant',
    thumbnail: '',
    colors: { primary: '#2D1B69', accent: '#A78BFA', text: '#1a1a2e', background: '#FFFFFF' },
    fonts: { heading: '"EB Garamond", Georgia, serif', body: '"EB Garamond", Georgia, serif' },
    layout: 'two-column',
    atsScore: 88,
    category: 'creative',
  },
  {
    id: 'developer',
    name: 'Developer',
    thumbnail: '',
    colors: { primary: '#0D1117', accent: '#00D9A6', text: '#c9d1d9', background: '#161B22' },
    fonts: { heading: '"DM Sans", system-ui, sans-serif', body: '"DM Sans", system-ui, sans-serif' },
    layout: 'two-column',
    atsScore: 90,
    category: 'creative',
  },
  {
    id: 'magazine',
    name: 'Magazine',
    thumbnail: '',
    colors: { primary: '#0D0D0D', accent: '#E53E3E', text: '#1a1a1a', background: '#FFFFFF' },
    fonts: { heading: '"Poppins", system-ui, sans-serif', body: '"Poppins", system-ui, sans-serif' },
    layout: 'two-column',
    atsScore: 82,
    category: 'creative',
  },
  {
    id: 'warm',
    name: 'Warm',
    thumbnail: '',
    colors: { primary: '#92400E', accent: '#F59E0B', text: '#1a0a00', background: '#FFFBF5' },
    fonts: { heading: '"Poppins", system-ui, sans-serif', body: '"Poppins", system-ui, sans-serif' },
    layout: 'two-column',
    atsScore: 89,
    category: 'creative',
  },
  {
    id: 'slate',
    name: 'Slate',
    thumbnail: '',
    colors: { primary: '#0F172A', accent: '#0EA5E9', text: '#1e293b', background: '#F8FAFC' },
    fonts: { heading: '"DM Sans", system-ui, sans-serif', body: '"DM Sans", system-ui, sans-serif' },
    layout: 'two-column',
    atsScore: 94,
    category: 'professional',
  },
  {
    id: 'bold',
    name: 'Bold',
    thumbnail: '',
    colors: { primary: '#09090B', accent: '#6366F1', text: '#3F3F46', background: '#FFFFFF' },
    fonts: { heading: '"Poppins", system-ui, sans-serif', body: '"Poppins", system-ui, sans-serif' },
    layout: 'two-column',
    atsScore: 87,
    category: 'creative',
  },
  {
    id: 'linea',
    name: 'Linea',
    thumbnail: '',
    colors: { primary: '#111827', accent: '#4F46E5', text: '#374151', background: '#FFFFFF' },
    fonts: { heading: '"DM Sans", system-ui, sans-serif', body: '"DM Sans", system-ui, sans-serif' },
    layout: 'two-column',
    atsScore: 91,
    category: 'minimal',
  },
  {
    id: 'academic',
    name: 'Academic',
    thumbnail: '',
    colors: { primary: '#1A1A1A', accent: '#1A1A1A', text: '#333333', background: '#FFFFFF' },
    fonts: { heading: '"EB Garamond", Georgia, serif', body: '"EB Garamond", Georgia, serif' },
    layout: 'single-column',
    atsScore: 99,
    category: 'professional',
  },
  {
    id: 'forest',
    name: 'Forest',
    thumbnail: '',
    colors: { primary: '#1B4332', accent: '#52B788', text: '#1C1C1C', background: '#FFFFFF', sidebar: '#1B4332' },
    fonts: { heading: '"DM Sans", system-ui, sans-serif', body: '"DM Sans", system-ui, sans-serif' },
    layout: 'two-column',
    atsScore: 88,
    category: 'professional',
  },
  {
    id: 'ocean',
    name: 'Ocean',
    thumbnail: '',
    colors: { primary: '#0A2540', accent: '#2D9CDB', text: '#2D3748', background: '#FFFFFF', sidebar: '#F0F6FF' },
    fonts: { heading: '"Inter", system-ui, sans-serif', body: '"Inter", system-ui, sans-serif' },
    layout: 'two-column',
    atsScore: 91,
    category: 'professional',
  },
  {
    id: 'night',
    name: 'Night',
    thumbnail: '',
    colors: { primary: '#000000', accent: '#555555', text: '#1A1A1A', background: '#FFFFFF' },
    fonts: { heading: '"Poppins", system-ui, sans-serif', body: '"Inter", system-ui, sans-serif' },
    layout: 'single-column',
    atsScore: 96,
    category: 'minimal',
  },
  {
    id: 'river',
    name: 'River',
    thumbnail: '',
    colors: { primary: '#000000', accent: '#000000', text: '#1A1A1A', background: '#FFFFFF' },
    fonts: { heading: 'Georgia, "Times New Roman", serif', body: 'Georgia, "Times New Roman", serif' },
    layout: 'single-column',
    atsScore: 99,
    category: 'professional',
  },
  {
    id: 'universe',
    name: 'Universe',
    thumbnail: '',
    colors: { primary: '#0F172A', accent: '#2563EB', text: '#374151', background: '#FFFFFF' },
    fonts: { heading: '"Inter", system-ui, sans-serif', body: '"Inter", system-ui, sans-serif' },
    layout: 'single-column',
    atsScore: 100,
    category: 'minimal',
  },
  {
    id: 'professional',
    name: 'Professional',
    thumbnail: '',
    colors: { primary: '#111827', accent: '#3B82F6', text: '#1A1A1B', background: '#FFFFFF' },
    fonts: { heading: '"Inter", system-ui, sans-serif', body: '"Inter", system-ui, sans-serif' },
    layout: 'two-column',
    atsScore: 98,
    category: 'professional',
  },
  {
    id: 'startup',
    name: 'Startup',
    thumbnail: '',
    colors: { primary: '#6366F1', accent: '#8B5CF6', text: '#1F2937', background: '#FFFFFF' },
    fonts: { heading: '"Inter", system-ui, sans-serif', body: '"Inter", system-ui, sans-serif' },
    layout: 'two-column',
    atsScore: 95,
    category: 'creative',
  },
  {
    id: 'leadership',
    name: 'Leadership',
    thumbnail: '',
    colors: { primary: '#1A1A2E', accent: '#7C3AED', text: '#111111', background: '#FFFFFF' },
    fonts: { heading: '"Cormorant Garamond", Georgia, serif', body: '"Lato", system-ui, sans-serif' },
    layout: 'single-column',
    atsScore: 94,
    category: 'professional',
  },
  {
    id: 'ats-opt',
    name: 'ATS Optimized',
    thumbnail: '',
    colors: { primary: '#000000', accent: '#000000', text: '#000000', background: '#FFFFFF' },
    fonts: { heading: '"Arial", sans-serif', body: '"Arial", sans-serif' },
    layout: 'single-column',
    atsScore: 100,
    category: 'minimal',
  },
  {
    id: 'timeline',
    name: 'Timeline',
    thumbnail: '',
    colors: { primary: '#0F172A', accent: '#3B82F6', text: '#334155', background: '#FFFFFF' },
    fonts: { heading: '"Inter", system-ui, sans-serif', body: '"Inter", system-ui, sans-serif' },
    layout: 'two-column',
    atsScore: 92,
    category: 'professional',
  },
  {
    id: 'grid-bento',
    name: 'Grid (Bento)',
    thumbnail: '',
    colors: { primary: '#6366F1', accent: '#8B5CF6', text: '#334155', background: '#F8FAFC' },
    fonts: { heading: '"Inter", system-ui, sans-serif', body: '"Inter", system-ui, sans-serif' },
    layout: 'two-column',
    atsScore: 88,
    category: 'creative',
  },
  {
    id: 'contrast',
    name: 'Contrast',
    thumbnail: '',
    colors: { primary: '#3B82F6', accent: '#60A5FA', text: '#334155', background: '#FFFFFF' },
    fonts: { heading: '"Inter", system-ui, sans-serif', body: '"Inter", system-ui, sans-serif' },
    layout: 'two-column',
    atsScore: 94,
    category: 'professional',
  },
  {
    id: 'matrix',
    name: 'Matrix (Skills)',
    thumbnail: '',
    colors: { primary: '#2563EB', accent: '#3B82F6', text: '#334155', background: '#FFFFFF' },
    fonts: { heading: '"Inter", system-ui, sans-serif', body: '"Inter", system-ui, sans-serif' },
    layout: 'two-column',
    atsScore: 90,
    category: 'professional',
  },
  {
    id: 'swiss',
    name: 'Swiss (Minimal)',
    thumbnail: '',
    colors: { primary: '#000000', accent: '#000000', text: '#1A1A1A', background: '#FFFFFF' },
    fonts: { heading: '"Inter", sans-serif', body: '"Inter", sans-serif' },
    layout: 'single-column',
    atsScore: 98,
    category: 'minimal',
  },
  {
    id: 'bold-sidebar',
    name: 'Bold Sidebar',
    thumbnail: '',
    colors: { primary: '#1E293B', accent: '#38BDF8', text: '#333333', background: '#FFFFFF' },
    fonts: { heading: '"Inter", sans-serif', body: '"Inter", sans-serif' },
    layout: 'two-column',
    atsScore: 93,
    category: 'professional',
  },
  {
    id: 'centric',
    name: 'Centric',
    thumbnail: '',
    colors: { primary: '#111827', accent: '#6366F1', text: '#1A1A1B', background: '#FFFFFF' },
    fonts: { heading: '"Inter", sans-serif', body: '"Inter", sans-serif' },
    layout: 'single-column',
    atsScore: 95,
    category: 'professional',
  },
  {
    id: 'linear',
    name: 'Linear',
    thumbnail: '',
    colors: { primary: '#000000', accent: '#000000', text: '#1A1A1B', background: '#FFFFFF' },
    fonts: { heading: '"Inter", sans-serif', body: '"Inter", sans-serif' },
    layout: 'single-column',
    atsScore: 97,
    category: 'minimal',
  },
  {
    id: 'bronzor',
    name: 'Bronzor (Premium)',
    thumbnail: '',
    colors: { primary: '#0f766e', accent: '#14b8a6', text: '#111827', background: '#FFFFFF', sidebar: '#0f172a' },
    fonts: { heading: '"DM Serif Display", serif', body: '"DM Sans", sans-serif' },
    layout: 'two-column',
    atsScore: 94,
    category: 'professional',
  },
];

// Preset color palettes for template customization
export const colorPalettes = [
  { name: 'Indigo', primary: '#1B2A4A', accent: '#3B82F6' },
  { name: 'Emerald', primary: '#064E3B', accent: '#10B981' },
  { name: 'Violet', primary: '#4C1D95', accent: '#8B5CF6' },
  { name: 'Crimson', primary: '#7F1D1D', accent: '#EF4444' },
  { name: 'Gold', primary: '#1A1A2E', accent: '#C9A84C' },
  { name: 'Teal', primary: '#134E4A', accent: '#14B8A6' },
  { name: 'Rose', primary: '#4A1942', accent: '#F43F5E' },
  { name: 'Slate', primary: '#0F172A', accent: '#64748B' },
  { name: 'Amber', primary: '#92400E', accent: '#F59E0B' },
  { name: 'Cyber', primary: '#0D1117', accent: '#00D9A6' },
];
