import React from 'react';
import type { Resume } from '../shared/types';
import { Mail, Phone, MapPin, Globe } from 'lucide-react';

interface Props {
  resume: Resume;
}

const ResumePreview: React.FC<Props> = ({ resume }) => {
  const { personal, experience, skills } = resume;

  return (
    <div className="resume-preview-wrapper">
      <div className="resume-preview-container print-area">
        {/* Design Accents */}
        <div className="accent-bar-top"></div>
        
        <header className="preview-header-premium">
          <div className="header-identity">
            <h1>{personal.name || 'YOUR NAME'}</h1>
            <div className="title-wrapper">
                <span className="title-line"></span>
                <h2 className="professional-title">{personal.title || 'PROFESSIONAL TITLE'}</h2>
                <span className="title-line"></span>
            </div>
          </div>
          
          <div className="contact-grid-premium">
            {personal.email && (
                <div className="contact-item">
                    <Mail size={12} />
                    <span>{personal.email}</span>
                </div>
            )}
            {personal.phone && (
                <div className="contact-item">
                    <Phone size={12} />
                    <span>{personal.phone}</span>
                </div>
            )}
            {personal.location && (
                <div className="contact-item">
                    <MapPin size={12} />
                    <span>{personal.location}</span>
                </div>
            )}
          </div>
        </header>

        <div className="resume-grid-premium">
          <div className="main-narrative">
            <section className="resume-section-premium">
              <h3 className="section-heading-premium">Professional Narrative</h3>
              <p className="summary-text">{personal.summary || 'A compelling summary of your career journey and unique value proposition.'}</p>
            </section>

            <section className="resume-section-premium">
              <h3 className="section-heading-premium">Career Journey</h3>
              {experience.length > 0 ? experience.map((exp) => (
                <div key={exp.id} className="experience-entry-premium">
                  <div className="entry-header">
                    <span className="company-name">{exp.company}</span>
                    <span className="entry-date">{exp.startDate} — {exp.endDate}</span>
                  </div>
                  <div className="role-title">{exp.role}</div>
                  <ul className="impact-bullets">
                    {exp.bullets.map((b, i) => (
                      <li key={i}>{b || 'Documented a significant achievement or responsibility...'}</li>
                    ))}
                  </ul>
                </div>
              )) : (
                <p className="placeholder-helper">Define your journey in the editor...</p>
              )}
            </section>
          </div>

          <aside className="side-narrative">
            <section className="resume-section-premium">
              <h3 className="section-heading-premium">Strategic Expertise</h3>
              <div className="expertise-tags">
                {skills.length > 0 ? skills.map((s) => (
                  <span key={s.id} className="expertise-tag">{s.name}</span>
                )) : (
                  <p className="placeholder-helper">Add your key competencies...</p>
                )}
              </div>
            </section>

            <section className="resume-section-premium">
                <h3 className="section-heading-premium">Core Passions</h3>
                <div className="passions-list-premium">
                    <div className="passion-entry">
                        <strong>Architecting</strong>
                        <span>Scalable Solutions</span>
                    </div>
                    <div className="passion-entry">
                        <strong>Mentoring</strong>
                        <span>High-Output Teams</span>
                    </div>
                </div>
            </section>
          </aside>
        </div>
        
        <footer className="preview-footer-premium">
            <span>Generated by Bespoke CV</span>
            <Globe size={10} />
            <span>bespokecv.com</span>
        </footer>
      </div>
    </div>
  );
};

export default ResumePreview;
